### ISSUE TITLE
PCIe Configuration Space

### ISSUE THREAD

**Issue by ryanvanleenen** [Cr4sh/zc_pcie_dma#1]
Hey,

You included a whole AXI core to read out the configuration space. The information from the configuration space is neat of course, but is there any specific reason as to why you wanted to read it out? You currently disabled writing to the configuration space. Is that functionality that you want to add, or is that not useful?

In any case, very interesting project! DMA attacks are nothing new, but the way that the target memory is made accessible is very impressive and I look forward to seeing more :)

Ryan

**Comment by Cr4sh** [comment]
> but is there any specific reason as to why you wanted to read it out? 

It might be useful for communication between some code running on the target (ie., backdoor or something like that) and some tools running on attacker machine (ie., ARM cores of Zynq processing system). To implement such communication you typically need to read/write data into the MMIO region of PCI-E device from the target and handle appropriate TLP packets on the attacker side. To handle such TLP packets in a proper way you need to know physical memory address of this MMIO region, it is stored in BAR register located in PCI configuration space, so, to obtain it you need to have some way to read the config space.

Also,  PCI configuration space access is necessary for option ROM emulation, check out this piece of code from my other FPGA project to see how exactly I implemented such feature: 
https://github.com/Cr4sh/s6_pcie_microblaze/blob/master/sdk/main_0/src/pcie_tlp.c#L154
`aixs_pcie_rom_address()` call is reading option ROM physical address from appropriate register of PCI configuration space and then this address is used to handle TLP packets from the target.

> Is that functionality that you want to add, or is that not useful?

Write support is not necessary for use cases described above. It would be really nice to have such feature, but Xilinx PCI-E hard IP core has very limited functionality of write access to the config space. As far as I remember, you can write only to the extended configuration space, maybe I'll implement it someday.
